export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';

export const FETCH_FULL_POST_START = 'FETCH_FULL_POST_START';
export const FETCH_FULL_POST_SUCCESS = 'FETCH_FULL_POST_SUCCESS';
export const FETCH_FULL_POST_ERROR = 'FETCH_FULL_POST_ERROR';
export const FETCH_POST_COMMENTS_SUCCESS = 'FETCH_POST_COMMENTS_SUCCESS';